version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '8000:8000'
    environment:
      MONGODB.DBHOST: "mongodb:27017"
      MONGODB.DBUSER: "root"
      MONGODB.DBPASSWORD: "password123"
    external_links:
      - mongodb
    networks:
      - dockerdev
    volumes:
      - ./resources:/app/resources
      - .:/app

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - dockerdev


volumes:
  mongodb:

networks:
  dockerdev:
    driver: bridge
